---
# tasks file for nginx

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install nginx
  apt:
    name: nginx 
    state: present

  become: yes

- name: Start nginx
  become: yes
  service:
    name: nginx
    state: started

- name: Copy VirtualHost to Target
  template: "src=../templates/wordpress.conf dest=/etc/nginx/sites-available/wordpress.conf owner=www-data group=www-data mode=0644"
  become: yes
  with_items:
          - "{{ servers }}"

- name: Enable site
  file: src=/etc/nginx/sites-available/wordpress.conf dest=/etc/nginx/sites-enabled/wordpress.conf owner=www-data group=www-data state=link
  notify:
    - restart nginx
  become: yes
